kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod-secret
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
      - name: HELLO
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: hello
