kind: ReplicationController
apiVersion: v1
metadata:
  name: myapp-rc
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: alpine
        command: ['sh', '-c', 'echo Hello Aulautil! && sleep 3600']
