---
environments:
  production:
    values:
    - production.yaml
  # Loading vars from remote
  cluster-azure-us-west:
    values:
      - git::https://github.com/rahulwagh/helmchart@helloworld?ref=master&sparse=0
---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: mario21ic
    url: https://mario21ic.github.io/helloworld-helmchart

releases:
  # From local
  - name: myhello-helmfile1
    chart: ./helloworld
    installed: true 
  #  #installed: false # to uninstall


  # Own repository
  - name: myhello-helmfile-github
    chart: mario21ic/helloworld
    installed: true

  # Community repository
  - name: prom-norbac-ubuntu
    namespace: prometheus
    chart: prometheus-community/prometheus
    set:
    - name: rbac.create
      value: false

  # From local
  - name: myhello-helmfile2
    chart: ./helloworld
    installed: true 
    values:
    - values.yaml.gotmpl

  # From local
  - name: myhello-helmfile3
    chart: ./helloworld
    installed: true 
    values:
    - foo:
          bar: "FOO_BAR3"

