kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-dp-cm
  annotations:
    #reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: "my-cm"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
          - name: MY_KEY
            valueFrom:
              configMapKeyRef:
                name: my-cm
                key: MY_KEY
          - name: foo
            value: "bar"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
