kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mypodviewer
  namespace: coolapp
subjects:
- kind: ServiceAccount
  name: myappid
  namespace: coolapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podreader
