apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
preemptionPolicy: PreemptLowerPriority # reemplazar a un pod de baja prioridad
globalDefault: false
description: "This priority class should be used for high-priority service pods only"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-nonpreemptive
value: 1000000
preemptionPolicy: Never # no va a reemplazar a pods de baja prioridad
globalDefault: false
description: "This priority class should be used for high-priority service pods only"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 500000
globalDefault: true # por defecto si no se especifica un priority class
description: "This priority class should be used for low-priority service pods only"
---
