apiVersion: v1
kind: Pod
metadata:
  name: nginx-high-priority-non-preemptive
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "2000m"
  priorityClassName: high-priority-nonpreemptive
