apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace
commonLabels:
  app: nginx
  env: qa
resources:
  - ../../base/
  - namespace.yaml
patchesStrategicMerge:
  - patch.yaml
namePrefix: qa-
#configMapGenerator:
#- name: nginx-configmap
#  files:
#    - appenv.conf.txt
