kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-dp
spec:
  replicas: 7
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-np-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx
    env: qa
  ports:
    - name: web
      port: 80 # intern
      targetPort: 80 # container

