apiVersion: v1
kind: Pod
metadata:
  name: alpine-privileged
  namespace: default
spec:
  containers:
    - image: alpine
      name: alpine
      command:
        - sleep
        - "3600"
      securityContext:
        privileged: true

