version: '3'

services:
  reverse-proxy:
    image: traefik:v1.7.16
    command: --docker --api --logLevel=info
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.mario21ic.com"
