kind: Pod
apiVersion: v1
metadata:
 name: java-liveness
spec:
 containers:
 - name: nginx
   image: mario21ic/liveness:java-v1
   livenessProbe:
     httpGet:
       path: /
       #path: /liveness
       port: 8080
     initialDelaySeconds: 5
     timeoutSeconds: 5
     periodSeconds: 10
     failureThreshold: 3
   readinessProbe:
     httpGet:
       path: /readiness
       port: 8080
     initialDelaySeconds: 10
     timeoutSeconds: 5
     periodSeconds: 5
     failureThreshold: 3
     successThreshold: 1
   ports:
     - containerPort: 8080
       name: http
       protocol: TCP

