version: '3.4'

services:
  proxy:
    image: traefik:v2.1
    command: --providers.docker --api.dashboard=true --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  nginx:
    image: nginx:alpine
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.mario21ic.com`)"

  apache:
    image: httpd:alpine
    labels:
      - "traefik.http.routers.apache.rule=Host(`apache.mario21ic.com`)"

