commonLabels:
  app: nginx
  env: prod
resources:
  - ../../base/
patchesStrategicMerge:
  - deploy.yaml
  - service.yaml
namePrefix: prod-
configMapGenerator:
  - name: nginx-configmap
    # behavior: create
    # behavior: merge
    behavior: replace
    files:
      - app.env
