commonLabels:
  app: nginx
  env: prod
resources:
  - ../../base/
patchesStrategicMerge:
  - deploy.yaml
  - service.yaml
namePrefix: prod-
configMapGenerator:
  - name: env-config
    files:
      - app.env
