kind: Service
apiVersion: v1
metadata:
  name: nginx-np-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx
    env: prod
  ports:
    - name: web
      port: 80 # intern
      targetPort: 80 # container

