apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgAQSInkTRXHQUNPH7LtU/Wxl02gLK6hDkzxZk8pnHUr8AAFmVgIxKfxx5ZKzYzy2ScQ8htUARq3Dyx9itY3Y5dI0Ywv6PgNsAJmVmTBS43uwHXVID5vKST4g91n3qMlW6s/W+4QLDMwPk3nCattKFJtIn5PjJo8tEC5BKDTPenmMTnc5FCkDVFSL6HhmymuZbopmrlklEPcAcJYhYDgnynKpyZhSfSQ+9pwCzyNDYJDEnwMm8634WffegdWw+YGYF5kfghygal3f9z1ihKqfRMv8w/nsCUBgEFDjxh+sXqGJfr9RvCosg2rmlyY7CA/K6bqWmBnDGc1LjL0HUx47N4fBeGAvAUcx4eVpiw3Vys3OhJ7WfTps3APbMR1NBNolYucKKnprlexNgMX0BqCTb/jV51vrESJP9CvGeVlK6LVq/AIzkFem2/yPWvPtJuaKo5+fU0NjGLKtFLZzCl8Flq0Iyl9DeyPi11XWL70ecIvY4QbOjFQSWbwt2JHL5iJoOQ5B7aGK0prUKO4CblwzmnuyBPrV0uQ7Ecdtb5HwtWUxuiZm3T6bBV1Z/jyjoF0m5xVYc7OQx2X/z5A3YPoR5B6REwgsKujsHZVjYhP6AHDtzCHtgMrH8nl3ppG3mfLeMXpmAZ/guWK0w0KwpsOSHDarjwQITK71Q9iPK7YBV5gBNLlC1YNpfLJJ7G8vzi32CuNF5U=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

