apiVersion: v1
kind: Pod
metadata:
 name: pod-privileged
spec:
 containers:
 - name: sec-ctx-3
   image: busybox:latest
   command: [ "sh", "-c", "sleep 1h" ]
   securityContext:
     allowPrivilegeEscalation: true

