kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: cluster-gpu
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
  - name: ng-2
    instanceType: g4dn.xlarge
    desiredCapacity: 2

