kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: demo1
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    availabilityZones: ["us-east-1a", "us-east-1b"]

