apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      command: ["bash", "-c", "sleep 36000"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
    #- name: digits-container
    #  image: nvidia/digits:6.0
    #  resources:
    #    limits:
    #      nvidia.com/gpu: 2 # requesting 2 GPUs

