kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod-cm
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
      - name: MY_KEY
        valueFrom:
          configMapKeyRef:
            name: my-cm
            key: MY_KEY
      - name: foo
        value: "bar"
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
