apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  #- 192.168.1.0/24
  - 192.168.1.54-192.168.1.59
  #- fc00:f853:0ccd:e799::/124
