kind: Pod
apiVersion: v1
metadata:
  name: custom-command-pod
spec:
  containers:
  - name: command-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep 5; done"]
