apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  volumes:
    - name: scratch-volume
      emptyDir: {}
  containers:
    - image: alpine
      name: alpine
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
