kind: Pod
apiVersion: v1
metadata:
  name: pod-cpu-demo
spec:
  containers:
  - name: pod-cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
