kind: Pod
apiVersion: v1
metadata:
 name: api-demo-sa
 labels:
   app: nginx
spec:
  serviceAccountName: demo-sa
  containers:
  - name: python-api
    image: mario21ic/service-account:python-v4
    ports:
      - name: web
        containerPort: 8080
        protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: api-demo-sa
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: web
      port: 8080 # intern
      nodePort: 32001 # node
      targetPort: 8080 # container
