kind: Deployment
apiVersion: apps/v1
metadata:
  #labels: # this will be exists after kustomize build base
  #  app: nginx
  name: nginx-dp
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mario21ic/nginx
        volumeMounts:
          - name: configmap-volume
            mountPath: /etc/nginx/vars/appenv.conf
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
      volumes:
        - name: "configmap-volume"
          configMap:
            name: "nginx-configmap"
