apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  volumes:
    - name: mi-volume
      persistentVolumeClaim:
        claimName: myclaim
  containers:
    - image: alpine
      name: alpine
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: /mnt/mydata
        name: mi-volume
