kind: PersistentVolume 
apiVersion: v1 
metadata:
  name: my-persistent-volume 
spec:
  capacity: 
    storage: 128M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/my-persistent-volume/
