kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  # Match con el pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
