kind: Pod 
apiVersion: v1 
metadata:
  name: pod-two
  # Important! Create this pod in the right namespace. 
  namespace: my-namespace
spec: 
  containers:
    - name: nginx-pod-two
      image: nginx:alpine
      resources:
        # This container requires at least 768m memory 
        # and 0.5 CPU resource to run
        requests:
          memory: 512m
          cpu: "0.5"
        # This container can use at most 1024m memory
        # and 2 CPU resources when it's running 
        limits:
          memory: 1024m 
          cpu: "2"
