kind: Pod 
apiVersion: v1 
metadata:
  name: pod-use-service-account
spec:
  # Set the service account containers in this pod 
  # use when they make requests to the API server 
  serviceAccountName: my-service-account 
  containers:
    - name: container-service-account 
      image: nginx:alpine
